[account]
# 账号配置(别忘记去掉注释"#")
# 单账号示例:
# 18888888888 = 'password'
# 多账号示例:
# 18888888888 = 'password'
# 19999999999 = 'password'

[message_push.server_chan]
# server酱推送key
send_key = ''

[message_push.wechat_message]
# 企业id
corpid = ''
# secret
corpsecret = ''
# agentid
agentid = ''